# -*- coding: utf-8 -*-
"""mini projects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSCom9YiXrSrg94lA4wGiyIeKgOn9V1Y
"""

#Password Generator – A script to generate random strong passwords.



import string #import string is used to import all the uppercase letters, lowercase letters, digits, nums and many more included in string
import random #import random helps in generating random characters

length = int(input('Enter password length : ')) # here we have used int because we want to add numbers in the user input. we can also use float instead of int if necessary

print('''choose character set for password from these :
          1. Letters
          2. Digits
          3. Special characters
          4. Exit''') # this menu is used for the types of characters we want to use in the password

characterList = "" # this empty string s
while(True):
    choice = int(input("Pick a number : "))
    if(choice == 1):

     characterList += string.ascii_letters  # using += because we are adding charactersets in the characterList and string.ascii_letters helps in uppercase and lowercase letters as "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

    elif(choice == 2):

     characterList += string.digits #string.digits adds numbers as "0123456789" in the characterList
    elif(choice == 3):

     characterList += string.punctuation #string.punctuation adds special characters as !"#$%&'()*+,-./:;<=>?@[\]^_{|}~ in the characterList

    elif(choice == 4):
         break    #break is used for exit

    else:
        print('Please pick a valid option!') # if there are none from the 4 choices in the user input it will say Please pick a valid option!

password = [] #[] are called as lists it will store the characters of the random password

for i in range(length): #The for loop runs as many times as the length of the password you want (for example, if you chose 8, it runs 8 times).
                       # we kept range as length and i is index
      randomcharacter = random.choice(characterList)
      password.append(randomcharacter)

print("The random password is : " + "".join(password))

